// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XjCEXoyChAb8NKjOBbsTH4T8M86HBtA',
    appId: '1:673201794334:web:562320dc0c624ba81aad0f',
    messagingSenderId: '673201794334',
    projectId: 'payroll-7c0fd',
    authDomain: 'payroll-7c0fd.firebaseapp.com',
    databaseURL: 'https://payroll-7c0fd-default-rtdb.firebaseio.com',
    storageBucket: 'payroll-7c0fd.firebasestorage.app',
    measurementId: 'G-MWXYZW28FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7EMqEFgR9uoOuWSXuQiMRCmJLlUhJH1E',
    appId: '1:673201794334:android:e7ee2d417a09b1621aad0f',
    messagingSenderId: '673201794334',
    projectId: 'payroll-7c0fd',
    databaseURL: 'https://payroll-7c0fd-default-rtdb.firebaseio.com',
    storageBucket: 'payroll-7c0fd.firebasestorage.app',
  );
}
